# This is a basic workflow to help you get started with Actions

name: Check the Dockerfile

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: build the docker image
        if: success()
        run: docker build -t philias/ubuntu:staging .

      - name: test the docker image
        if: success()
        run: docker run -d -i -t --name philias-ubuntu-staging -p 4144:80 -p 41440:22 philias/ubuntu:staging

      - name: Ask for approval
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.MY_PIPELINE_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Please review the pull request.
            If approved please comment "approve".
            Otherwise make comments on the code, or to close the pull request comment "abort".

      - name: Merge pull request
        if: success() && contains(github.event.comment.body, 'approve')
        uses: actions/github-script@v4
        with:
          script: |
            const { context, github } require('@actions/github');
            const prNumber = context.payload.pull_request.number;
            const mergeMethod = 'merge';

            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: mergeMethod
            });