name: Check the Dockerfile

on:
  pull_request:
    branches: [ "main" ]
    types: [ opened, synchronize, reopened ]

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  check-the-code:
    runs-on: ubuntu-latest

    steps:
      - name: Checking the code
        uses: actions/checkout@v3

  build--test-the-docker-image:
    runs-on: ubuntu-latest
    needs: check-the-code

    steps:
      - name: Checking the code
        uses: actions/checkout@v3

      - name: Build the docker image
        run: docker build -t philias/ubuntu:staging .

      - name: Test the docker image
        if: success()
        run: docker run -d -i -t --name philias-ubuntu-staging -p 4144:80 -p 41440:22 philias/ubuntu:staging

  ask-for-approval:
    runs-on: ubuntu-latest
    needs: build--test-the-docker-image

    steps:
      - name: Ask for approval
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.MY_PIPELINE_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Please review the pull request.
            If approved please comment "approve".
            Otherwise make comments on the code, or to close the pull request comment "abort".
