name: Check the comments

on:
  issue_comment:
    types: [created]

jobs:
  approve-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Merge pull request
        if: contains(github.event.comment.body, 'approve')
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_PIPELINE_TOKEN }}
          script: |
            const { github } require('@actions/github');
            const prNumber = context.payload.pull_request.number;
            const mergeMethod = 'merge';

            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              merge_method: mergeMethod
            });
        