name: Check the comments

on:
  issue_comment:
    types: [created]

jobs:
  approve-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Merge pull request
        if: contains(github.event.comment.body, '/approve')
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.MY_PIPELINE_TOKEN }}
          pull-request-number: ${{ github.event.pull_request.number }}
        