name: Check the comments

on:
  issue_comment:
    types: [created]

jobs:
  approve-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Merge pull request
        if: contains(github.event.comment.body, 'approve')
        uses: "pascalgn/automerge-action@v0.15.6"
        env:
          GITHUB_TOKEN: "${{ secrets.MY_PIPELINE_TOKEN }}"
        